### ISSUE TITLE
Does the sponge not dry water?

### ISSUE THREAD

**Issue by Estem01** [kotyaralih/NostalgiaCore#25]
Add the possibility of the sponge dry the water

**Comment by GameHerobrine** [comment]
does sponge absorb water in vanilla?

**Comment by Estem01** [comment]
no @GameHerobrine

**Comment by GameHerobrine** [comment]
well then it *might* be added as feature i guess =D

**Comment by GameHerobrine** [comment]
although idk when

**Comment by Estem01** [comment]
So it is good :)

**Comment by GameHerobrine** [comment]
*um yeah i guess ill mark it as closed?*
