### ISSUE TITLE
TextFormat::toHTML() is broken

### ISSUE THREAD

**Issue by Sunch233** [kotyaralih/NostalgiaCore#45]
In src/utils/TextFormat.php
the toHTML method uses constants of the new API, such as `TextFormat::BOLD` , but in fact they should use constants of the old API such as `FORMAT_BOLD` , which causes the function to be unavailable

**Comment by kotyaralih** [comment]
should be fixed in https://github.com/kotyaralih/NostalgiaCore/commit/26b2f0534ddb3ba312eb61de3ede4ef5ca9a0728
